using TelltaleToolKit.Reflection;
using TelltaleToolKit.Serialization;
using TelltaleToolKit.Serialization.Serializers;

namespace TelltaleToolKit.T3Types.Meshes.T3Types;

[MetaClassSerializerGlobal(typeof(DefaultClassSerializer<T3MeshEffectPreloadEntry>))]
public class T3MeshEffectPreloadEntry
{
    [MetaMember("mEffectType")]
    public uint EffectType { get; set; }

    [MetaMember("mStaticEffectFeatures")]
    public BitSetBase StaticEffectFeatures { get; set; }

    [MetaMember("mMaterialCRC")]
    public ulong MaterialCRC { get; set; }

    [MetaMember("mDynamicEffectFeatures")]
    public List<T3MeshEffectPreloadDynamicFeatures> DynamicEffectFeatures { get; set; }
}

// TODO:
// No idea if this is WDC exclusive
// The effect type is serialized as a regular uint.
// Probably because there are different effect for each platform?
// But then - there would have been metaflags for it.
[MetaClassSerializerGlobal(typeof(EnumSerializer<T3EffectType>))]
public enum T3EffectType
{
	// WDC_eEffect_
	Mesh = 0x0,
	Particle = 0x1,
	ParticleGlow = 0x2,
	ParticleForceLinearDepth = 0x3,
	Particle_Xbox_Instanced = 0x4,
	DeferredDecalGBuffer = 0x5,
	DeferredDecalEmissive = 0x6,
	DeferredDecalGlow = 0x7,
	SceneSimple = 0x8,
	SceneSimple_Texture = 0x9,
	SceneSimple_Cone = 0x0A,
	SceneNPRLinesCS_Rasterize = 0x0B,
	SceneNPRLinesCS_ForceLinearDepth = 0x0C,
	ScenePreZ = 0x0D,
	ScenePreZLines = 0x0E,
	ForceLinearDepth = 0x0F,
	SceneShadowMap = 0x10,
	SceneGlow = 0x11,
	SceneGBuffer = 0x12,
	SceneGBufferLines = 0x13,
	SceneToonOutline = 0x14,
	SceneToonOutline2 = 0x15,
	SceneToonOutline2_GBuffer = 0x16,
	FX_GlowPrepare = 0x17,
	FX_Glow = 0x18,
	FX_DepthOfFieldPrepare = 0x19,
	FX_GaussianBlur = 0x1A,
	FX_GaussianBlur_Glow = 0x1B,
	FX_GaussianBlur_Outline = 0x1C,
	FX_BlurUp = 0x1D,
	FX_MotionBlur = 0x1E,
	FX_MergeColorDepth = 0x1F,
	FX_PostColor = 0x20,
	DynamicLightMap = 0x21,
	FX_RadialBlur = 0x22,
	FX_FXAA = 0x23,
	FX_SMAA_EdgeDetect = 0x24,
	FX_SMAA_BlendWeight = 0x25,
	FX_SMAA_Final = 0x26,
	FX_GBufferResolve = 0x27,
	FX_GBufferDownSample = 0x28,
	FX_LinearDepthDownSample = 0x29,
	FX_DepthDownSample = 0x2A,
	FX_StencilMaskRestore = 0x2B,
	FX_OcclusionFilter = 0x2C,
	FX_Null = 0x2D,
	FX_Copy = 0x2E,
	FX_CopyDepth = 0x2F,
	FX_CompositeAlpha = 0x30,
	FX_CompositeQuarter = 0x31,
	FX_CreateOutlineSrc = 0x32,
	FX_CreateOutline = 0x33,
	FX_BrushOutline = 0x34,
	FX_BrushOutline_Simple = 0x35,
	FX_BrushOffsetApply = 0x36,
	FX_BrushOutlineBlurPrepare = 0x37,
	FX_BrushOutlineBlur = 0x38,
	FX_ApplyModulatedShadow = 0x39,
	FX_FinalResolve = 0x3A,
	FX_FinalDebugOverlay = 0x3B,
	SceneText = 0x3C,
	SceneSimple_Texture_AlphaOnly = 0x3D,
	SceneHLSMovieYUV = 0x3E,
	SceneHLSMovieRGB = 0x3F,
	DirectionalLightShadow = 0x40,
	DirectionalLightShadow_High = 0x41,
	ProjectedTextureShadow = 0x42,
	ProjectedTextureColor = 0x43,
	EnvLightShadowMark_Point = 0x44,
	EnvLightShadowMark_Spot = 0x45,
	EnvLightShadowApply_Point = 0x46,
	EnvLightShadowApply_Spot = 0x47,
	EnvLightShadowApply_Directional = 0x48,
	EnvLightShadowApply_DirectionalFade = 0x49,
	EnvLightShadowApply_DirectionalBlend = 0x4A,
	EnvLightShadowApply_SDSM_Directional = 0x4B,
	EnvLightShadowApply_SDSM_DirectionalFade = 0x4C,
	ShadowMark_SDSM = 0x4D,
	ShadowVolumeApply = 0x4E,
	ShadowTrace = 0x4F,
	ShadowTrace_HBAOLow = 0x50,
	ShadowTrace_HBAOMid = 0x51,
	ShadowTrace_HBAOHigh = 0x52,
	ShadowTrace_MSAA = 0x53,
	ShadowTrace_HBAOLow_MSAA = 0x54,
	ShadowTrace_HBAOMid_MSAA = 0x55,
	ShadowTrace_HBAOHigh_MSAA = 0x56,
	FX_DeferredFilter_Light = 0x57,
	FX_DeferredFilter_Shadow = 0x58,
	FX_DeferredFilter_LightShadow = 0x59,
	FX_CreateOutlineSrcQuarter = 0x5A,
	FX_NewGlowH1x = 0x5B,
	FX_NewGlowV1x = 0x6B,
	FX_NewGlowPresent = 0x7B,
	FX_NewDepthOfFieldPreparE, alf = 0x7C,
	FX_DepthOfFieldBlurH1x = 0x7D,
	FX_DepthOfFieldBlurV1x = 0x7E,
	FX_DepthOfFieldBlurH = 0x7F,
	FX_DepthOfFieldBlurV = 0x80,
	FX_DepthOfFieldBlurHNear = 0x81,
	FX_DepthOfFieldBlurHFar = 0x82,
	FX_DepthOfFieldBlurVNear = 0x83,
	FX_DepthOfFieldBlurVFar = 0x84,
	FX_ShadowFilter_Pass0 = 0x85,
	FX_ShadowFilter_Pass0_TAA = 0x86,
	FX_ShadowFilter_Blur0 = 0x87,
	FX_ShadowFilter_Blur1 = 0x88,
	FX_HBAOLowestQuality = 0x89,
	FX_HBAOLowQuality = 0x8A,
	FX_HBAOMediumQuality = 0x8B,
	FX_HBAOHighQuality = 0x8C,
	FX_HBAOHighestQuality = 0x8D,
	FX_HBAODeinterleaveDepth = 0x8E,
	FX_HBAODeinterleaveNormals = 0x8F,
	FX_HBAOReinterleave = 0x90,
	FX_SSLines = 0x91,
	FX_SSLinesResolve_1x_Pass0 = 0x92,
	FX_SSLinesResolve_1x_Pass1 = 0x93,
	FX_SSLinesResolve_2x_Pass0 = 0x94,
	FX_SSLinesResolve_2x_Pass1 = 0x95,
	FX_SSLinesResolve_3x_Pass0 = 0x96,
	FX_SSLinesResolve_3x_Pass1 = 0x97,
	FX_SSLinesResolve_4x_Pass0 = 0x98,
	FX_SSLinesResolve_4x_Pass1 = 0x99,
	FX_MSAAResolve_2x = 0x9A,
	FX_MSAAResolve_4x = 0x9B,
	FX_MSAAResolve_8x = 0x9C,
	FX_MSAASceneResolve_2x = 0x9D,
	FX_MSAASceneResolve_4x = 0x9E,
	FX_MSAASceneResolve_8x = 0x9F,
	FX_SceneResolve_TAA = 0x0A0,
	FX_MSAASceneResolve_TAA_2x = 0x0A1,
	FX_MSAASceneResolve_TAA_4x = 0x0A2,
	FX_MSAASceneResolve_TAA_8x = 0x0A3,
	FX_MSAAGBufferResolve_2x = 0x0A4,
	FX_MSAAGBufferResolve_4x = 0x0A5,
	FX_MSAAGBufferResolve_8x = 0x0A6,
	MakeMipLevel = 0x0A7,
	MakeMipLevel_BlurH = 0x0A8,
	MakeMipLevel_BlurV = 0x0A9,
	MakeMipLevel_Array = 0x0AA,
	CS_ComputeTest = 0x0AB,
	CS_ApplySkinning_0Normal = 0x0AC,
	CS_ApplySkinning_1Normal = 0x0AD,
	CS_ApplySkinning_2Normal = 0x0AE,
	CS_ApplySkinning_3Normal = 0x0AF,
	CS_ApplySkinning_Float3Position_0Normal = 0x0B0,
	CS_ApplySkinning_Float3Position_1Normal = 0x0B1,
	CS_ApplySkinning_Float3Position_2Normal = 0x0B2,
	CS_ApplySkinning_Float3Position_3Normal = 0x0B3,
	CS_LineGeneration = 0x0B4,
	CS_ClearIndirectDraw = 0x0B5,
	CS_LightClustering2D = 0x0B6,
	CS_LightClustering3D = 0x0B7,
	CS_ShadowCascadeDistances_Manual = 0x0B8,
	CS_ShadowCascadeDistances_Auto = 0x0B9,
	CS_ShadowCascadeBounds_Pass0 = 0x0BA,
	CS_ShadowCascadeBounds_PassN = 0x0BB,
	CS_ShadowCascades = 0x0BC,
	CS_ShadowCascades_ComputedBounds = 0x0BD,
	CS_CullShadowCasters = 0x0BE,
	CS_EnvLightMakeEVSM_Linear_Blur0 = 0x0BF,
	CS_EnvLightMakeEVSM_Linear_Blur3x3 = 0x0C0,
	CS_EnvLightMakeEVSM_Linear_Blur9x9 = 0x0C1,
	CS_EnvLightMakeEVSM_NonLinear_Blur0 = 0x0C2,
	CS_EnvLightMakeEVSM_NonLinear_Blur3x3 = 0x0C3,
	CS_EnvLightMakeEVSM_NonLinear_Blur9x9 = 0x0C4,
	CS_DepthReduction_Pass0_8x8 = 0x0C5,
	CS_DepthReduction_Pass0_16x16 = 0x0C6,
	CS_DepthReduction_PassN = 0x0C7,
	CS_DepthReduction_PassFinal = 0x0C8,
	CS_BokehSprites = 0x0C9,
	FX_RasterizeBokeh = 0x0CA,
	CS_EnlightenMakeDusters_Point = 0x0CB,
	CS_EnlightenMakeDusters_Spot = 0x0CC,
	CS_EnlightenMakeDusters_Directional = 0x0CD,
	CS_WaveformMonitor = 0x0CE,
	CS_EnvLightApplyDeferred = 0x0CF,
	CS_EnvLightApplyDeferred_LowRes = 0x0D0,
	BakeObjectNormals_Tool = 0x0D1,
	BakeObjectNormals_NormalMap_Tool = 0x0D2,
	BakeTangentNormals_Tool = 0x0D3,
	BakeLighting_Tool = 0x0D4,
	CS_LightmapBlurH_Tool = 0x0D5,
	CS_LightmapBlurV_Tool = 0x0D6,
	CS_LightmapFilter_Tool = 0x0D7,
	CS_LightmapConvert_Tool = 0x0D8,
	CS_BakeShadowVolume_Tool = 0x0D9,
	CS_ComputeAsyncTest = 0x0DA,
	Count = 0x0DB,
	WDC_eEffect_None = -1,
}